config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments
  end
  resources :my_articles, only: [:index]
  resources :statics, only: [:index]
  devise_for :users

  root 'articles#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  acts_as_taggable

  paginates_per 5

  before_save :ensure_published_at
  before_create :ensure_published_at

  scope :published, -> { where(is_published: true) }

  def ensure_published_at
    self.published_at = created_at if published_at.blank?
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :can_be_edited?

  def can_be_edited?(object)
    ::AccessChecker.new(current_user, object).call
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]

  def index
    @articles = ArticleRelationBuilder.new(params).call
  end

  def show
    @comments = @article.comments.order(id: :desc).includes(:user)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :content, :published_at, :is_published, :tag_list)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article, :authenticate_user!
  before_action :set_comment, :can_comment_be_edited?, only: [:destroy, :update, :edit]

  def new
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.article = @article

    respond_to do |format|
      if @comment.save
        format.html { redirect_to article_url(@article), notice: 'Comment was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    @comment.update(comment_params)
    redirect_to article_url(@article), notice: 'Comment was successfully updated.'
  end

  def destroy
    @comment.destroy
    redirect_to article_url(@article), notice: 'Comment was successfully destroyed.'
  end

  private
  def set_article
    @article = Article.find(params[:article_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def can_comment_be_edited?
    redirect_to article_url(@article) unless can_be_edited?(@comment)
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/my_articles_controller.rb
class MyArticlesController < ApplicationController
  before_action :authenticate_user!

  def index
    @articles = ArticleRelationBuilder.new(params).call_for_user(current_user.id)
    render 'articles/index'
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.haml
= form_for(@article) do |f|
  - if @article.errors.any?
    #error_explanation
      %h2
        = pluralize(@article.errors.count, "error")
        prohibited this article from being saved:
      %ul
        - @article.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    %br
    = f.text_field :title
  .field
    = f.label :tag_list, 'Tags (with comma separator)'
    %br
    = f.text_field :tag_list
  .field
    = f.label :content
    %br
    = f.text_area :content
  .field
    = f.label :published_at, 'Created at'
    %br
    = f.datetime_select :published_at
  .field
    = f.label :is_published
    %br
    = f.check_box :is_published
  .actions
    = f.submit

app/views/articles/edit.html.haml
%h1 Editing Article
= render 'form'
= link_to 'Show', @article
|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
#cloud__block
  %p Tags cloud:
  - tag_cloud Article.tag_counts, %i(small medium large) do |tag, css_class|
    = link_to tag.name, url_for(tag: tag.name), class: css_class
%br
%br
#articles__block
  %p#notice= notice

  %h1 Listing Articles
  %br

  - @articles.each do |article|
    .article
      %p= link_to article.title, article
      %p= "#{article.published_at.to_formatted_s(:long)} | #{article.user.email}"
      %p= article.content
      %p
        %b
          TAGS:
        = raw article.tag_list.map { |t| link_to t, url_for(tag: t) }.join(', ')

      - if can_be_edited?(article)
        = link_to 'Edit', edit_article_path(article)
        |
        = link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }
    %br

  %br
  = paginate @articles

app/views/articles/new.html.haml
%h1 New Article
= render 'form'
= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @article.title
%p
  %strong Tags:
  =raw @article.tag_list.map { |t| link_to t, articles_path(tag: t) }.join(', ')
%p
  %strong Content:
  = @article.content
%p
  %strong Created at:
  = @article.published_at.to_formatted_s(:long)
%p
  %strong User:
  = @article.user.email
- if can_be_edited?(@article)
  = link_to 'Edit', edit_article_path(@article)
  |
  = link_to 'Destroy', @article, method: :delete
  |
= link_to 'Back', articles_path


#article__comments
  - @comments.each do |comment|
    %br
    = render 'comments/comment', comment: comment

  %br
  %h2 New Comment
  = render 'comments/form'

app/views/comments/_comment.html.haml
#comment__block
  %p
    = "#{comment.user.email}   |  #{comment.created_at.to_formatted_s(:long)}"
  %p
    = comment.content

  - if can_be_edited?(comment)
    = link_to 'Edit', edit_article_comment_path(@article, comment)
    |
    = link_to 'Destroy', [@article, comment], method: :delete

app/views/comments/_form.html.haml
= form_for([@article, @comment ||= Comment.new]) do |f|
  - if @article.errors.any?
    #error_explanation
      %h2
        = pluralize(@comment.errors.count, "error")
        prohibited this article from being saved:
      %ul
        - @comment.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :content
    %br
    = f.text_area :content
  .actions
    = f.submit

app/views/comments/edit.html.haml
%h1 Editing Comment
= render 'form'
= link_to 'Back', articles_path

app/views/comments/new.html.haml
%h1 New Comment
= render 'form'
= link_to 'Back', @article

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TestBlog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    #wrapper
      #navigation
        = link_to 'Home', root_path
        |
        - if current_user
          = link_to 'Sign out', destroy_user_session_path, method: :delete
          |
          = link_to 'My articles', my_articles_path
          |
          = link_to 'New Article', new_article_path
          |
        - else
          = link_to 'Sign in', new_user_session_path
          |
          = link_to 'Sign up', new_user_registration_path
          |
        = link_to 'Statics', statics_path
      #content
        = yield
      #footer

app/views/statics/index.html.haml
#statics__block
  #caruosel
    .slide-wrapper.js__slide-0
      .slide.slide-face
        .slide-content__wrapper
          .slide__content
            %table
              %tr
                %td.slide__content__arrows
                  %span.slide-arrow.js__arrow{ data: { number: 2 } }
                    «
                  %span.slide-arrow.js__arrow{ data: { number: 1 } }
                    »
                %td.slide__content__text
                  Фотографиям вашего ребенка позавидуют даже звезды
                %td.slide__content__button
                  %a.yellow_button{href: '#'}
                    НАЧАТЬ ОБУЧЕНИЕ »


    .slide-wrapper.js__slide-1
      .slide.slide-gate
        .slide-content__wrapper
          .slide__content
            %table
              %tr
                %td.slide__content__arrows
                  %span.slide-arrow.js__arrow{ data: { number: 0 } }
                    «
                  %span.slide-arrow.js__arrow{ data: { number: 2 } }
                    »
                %td.slide__content__text
                  Какие-то ворота в Индии во время грозы
                %td.slide__content__button
                  %a.yellow_button{href: '#'}
                    НАЧАТЬ ОБУЧЕНИЕ »

    .slide-wrapper.js__slide-2
      .slide.slide-motocycle
        .slide-content__wrapper
          .slide__content
            %table
              %tr
                %td.slide__content__arrows
                  %span.slide-arrow.js__arrow{ data: { number: 1 } }
                    «
                  %span.slide-arrow.js__arrow{ data: { number: 0 } }
                    »
                %td.slide__content__text
                  Таким фотографиям все тоже позавидуют
                %td.slide__content__button
                  %a.yellow_button{href: '#'}
                    НАЧАТЬ ОБУЧЕНИЕ »